table Sentiment
	lineageTag: 84f55922-345e-476d-8f64-aa9ad68a5e88

	column 'Sentiment Classification'
		dataType: string
		lineageTag: 7a391df3-3ced-4744-9d1e-95a1d9779073
		summarizeBy: none
		sourceColumn: Sentiment Classification
		sortByColumn: 'Sentiment Score'

		annotation SummarizationSetBy = Automatic

	column 'Sentiment Score'
		dataType: int64
		formatString: 0
		lineageTag: f7f16885-1ffb-4637-a269-146e7c00d1c1
		summarizeBy: none
		sourceColumn: Sentiment Score

		annotation SummarizationSetBy = Automatic

	column 'Sentiment Result - SVG' =
			
			VAR _Status = Sentiment[Sentiment Classification]
			VAR _colour = SWITCH(_Status,
			                        "Unhappy","#DE1A24",
			                        "Happy","#1EA185","#6089B1"
			)
			RETURN
			
			IF(_Status= BLANK(),BLANK(),
			"data:image/svg+xml;utf8," &
			"
			<svg width='532' height='137' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' xml:space='preserve' overflow='hidden'><g transform='translate(-2898 -1770)'><path d='M2899.5 1771.5 3394.2 1771.5 3428.5 1805.8 3428.5 1889.5 3428.5 1889.5 2933.8 1889.5 2899.5 1855.2 2899.5 1771.5Z' stroke='"&_colour&"' stroke-width='0.4375' stroke-miterlimit='8' fill='"&_colour&"' fill-rule='evenodd' fill-opacity='0.2'/><text fill='"&_colour&"' font-family='Calibri,Calibri_MSFontService,sans-serif' font-weight='700' font-size='64' transform='matrix(1 0 0 1 2948.97 1851)'>"&_Status&"</text></g></svg>
			"
			)
		lineageTag: 2a8dfa2a-9d97-4c8a-8145-8711747b11d5
		dataCategory: ImageUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Sentiment-169b94ac-2d60-45bb-a981-5d7412f19ce1 = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Quelle = #"Sentiment Outcomes 1",
				    #"Angefügte Abfrage" = Table.Combine({Quelle, #"Sentiment Outcomes 2"}),
				    #"Entfernte Duplikate" = Table.Distinct(#"Angefügte Abfrage"),
				    #"Hinzugefügte benutzerdefinierte Spalte" = Table.AddColumn(#"Entfernte Duplikate", "Sentiment Score", each if [Sentiment Classification] = "Unhappy" then -1 else if [Sentiment Classification] = "Happy" then 1 else 0, Int64.Type)
				in
				    #"Hinzugefügte benutzerdefinierte Spalte"

	annotation PBI_ResultType = Table

